### PR TITLE
rfc1035label: support compression pointers

### LINKED ISSUE #203: Implement DNS compression in rfc1035label package
Label compression is not implemented, I have hit a DHCP server that responds with compressed labels and the library failed to parse the response

### PR DESCRIPTION
**Pull request by insomniacslk**
The `rfc1035label` module did not support compressed labels, now it does.

Fixes #203

### CODE REVIEW

File: rfc1035label/label_test.go [hunk 1]
```diff
@@ -52,15 +42,85 @@ func TestLabelToBytes(t *testing.T) {
...
+		// slackware.it
+		9, 's', 'l', 'a', 'c', 'k', 'w', 'a', 'r', 'e',
+		2, 'i', 't',
+		0,
+		// insomniac.slackware.it
+		9, 'i', 'n', 's', 'o', 'm', 'n', 'i', 'a', 'c',
+		192,
+	}
+
+	_, err := LabelsFromBytes(data)
```
Comment (pmazzini) [inline rfc1035label/label_test.go]: Should the return value also be tested?

File: rfc1035label/label_test.go [hunk 2]
```diff
@@ -52,15 +42,85 @@ func TestLabelToBytes(t *testing.T) {
...
+		3, 'i', 't',
+		0,
+		// slackware.it
+		9, 's', 'l', 'a', 'c', 'k', 'w', 'a', 'r', 'e',
+		192, 0,
+		// insomniac.slackware.it
+		9, 'i', 'n', 's', 'o', 'm', 'n', 'i', 'a', 'c',
+		192, 5,
 	}
+	_, err := LabelsFromBytes(data)
```
Comment (pmazzini) [inline rfc1035label/label_test.go]: Should the return value also be tested?

File: rfc1035label/label.go [hunk 3]
```diff
@@ -1,39 +1,62 @@
...
+				return nil, errors.New("rfc1035label: cannot handle nested pointers")
+			}
+			handlingPointer = true
+			if pos+1 > len(buf) {
+				return nil, errors.New("rfc1035label: pointer buffer too short")
+			}
+			off := int(buf[pos-1]&^0xc0)<<8 + int(buf[pos])
+			oldPos = pos + 1
+			pos = off
+			continue
```
[the remark this answers is not in the document]
Comment (insomniacslk) [reply rfc1035label/label.go]: not anymore, it's a leftover from the previous iteration, thanks!

File: rfc1035label/label_test.go (hunk 1 above)
Comment (insomniacslk) [reply rfc1035label/label_test.go]: not in this case - the function returns an error from the invalid data, no valid data is expected to be returned

File: rfc1035label/label_test.go (hunk 2 above)
Comment (insomniacslk) [reply rfc1035label/label_test.go]: same as above

File: rfc1035label/label_test.go (hunk 1 above)
Comment (pmazzini) [reply rfc1035label/label_test.go]: Oh right
